### ISSUE TITLE
suggestion: include rsync

### ISSUE THREAD

**Issue by adamf663** [Zackptg5/Cross-Compiled-Binaries-Android#46]
Title says it all

**Comment by Zackptg5** [comment]
So there's an existing module already with rclone here: https://github.com/piyushgarg/rclone-mount

Binaries are out of date there so I may add them if I get the chance

**Comment by Zackptg5** [comment]
So turns out you can just download pre-compiled binaries at there main download page: https://rclone.org/downloads

It'd be better to just use the existing rclone-mount module above and replace the rclone binary with the updated one but it's been broken for a while due to the dev mounting to /sbin which no longer exists in A11+ so I'll look into adding it to ccbins

**Comment by Zackptg5** [comment]
Updated the existing module so it'll work now: https://github.com/Zackptg5/rclone-mount

I'll work on adding rclone to ccbins

**Comment by Zackptg5** [comment]
Done
