### ISSUE TITLE
Android 4.4 support

### ISSUE THREAD

**Issue by smopro** [Zackptg5/Cross-Compiled-Binaries-Android#57]
Have x86 tablet with 4.4 - entware not useful in more cases, how to build (API 19)? Or what project more useful on android with as minimal binutils, gnu utils?

**Comment by Zackptg5** [comment]
Static binaries will work regardless of api so you could use them. The DNS issues with curl and aria2 don't apply to android older than Oreo.


If you want to compile dynamic linked bins, you can clone the build_script folder and run the build script specifying api level (use 
`./build.sh -h` to see usage).


Note that some of the binaries have minimum api levels due to to bionic issues so if you're api value is overwritten by the script, that's why. I haven't tested anything with older api than 21 so you will likely encounter some errors one some of them.

**Comment by smopro** [comment]
Thx for answer. I have BusyBox - Stephen (Stericson). Today i want remove entware and build normal "system" in opt with full-featured software - normal binutils, gnu utils for compiling software from sources on my device without crosscompiling
