### ISSUE TITLE
bash-v5.1.12(1)-arm64: backspace not working

### ISSUE THREAD

**Issue by seffparker** [Zackptg5/Cross-Compiled-Binaries-Android#62]
After updating to the latest version 5.1.12(1), the `backspace` and `ctrl + w` doesn't works. It creates unintended results like tab character or makes the terminal session unresponsive.

No such issues in previous version 5.1.8

**Environment:**
Device: Xiaomi POCO F1
OS: Android 10
Terminal: Termux 0.117
Keyboard: Google Gboard
Root: Magisk

**Comment by Zackptg5** [comment]
Can you try with a different terminal app? Termux uses a custom environment that messes with the paths some of my binaries rely on. I recommend using termux binaries for termux use.
I use termius myself and am unable to replicate this problem there

**Comment by Zackptg5** [comment]
Think I figured out why there's been the change in behavior on random elements with bash: using newer readline dependency rather than built-in bash readline.
I'm going to recompile with built-in readline like I used to (also update to patch level 16 in the process), should fix all of this. 
I'm also going to move away from using sdcard in the near future since that's become more locked down in recent android versions

**Comment by Zackptg5** [comment]
Yup, that was it. Will be pushing fixes outlined above

**Comment by SedapnyaTidur** [comment]
You could also fix that using custom bindings in your `.inputrc` file in $HOME directory. Here is mine looks like:
```bash
# Ctrl-X Ctrl-R: Reload this file
"\C-x\C-r": re-read-init-file
# Tab: menu complete
"\t": menu-complete
# Del: forward delete
"\e[3~": delete-char
# Ctrl-L: clear screen
"\C-l": clear-screen
# Esc-Right arrow: Move cursor to next word
"\e\e[C": shell-forward-word
# Esc-Left arraw: Move cursor to previous word
"\e\e[D": shell-backward-word
# Esc-Up arrow: Uppercase word
"\e\e[A": upcase-word
# Esc-Down arrow: Lowercase word
"\e\e[B": downcase-word
# Esc-Del: Disable deletion
"\e\e[3~": ""
# Esc-Backspace: Disable deletion
"\e\177": ""
```
