### ISSUE TITLE
.bashrc file in $HOME is ignored

### ISSUE THREAD

**Issue by SedapnyaTidur** [Zackptg5/Cross-Compiled-Binaries-Android#77]
**Describe the bug**
Latest version of `bash` does not respect `.bashrc` file in $HOME directory.
**To Reproduce**
  - Create a simple `.bashrc` file in $HOME like following:
```
echo "echo 'Hello World'" > "$HOME"/.bashrc
```
  - Install the bash command and run it.

**Expected behavior**
Print `Hello World` on terminal.
**Screenshots**

**Device Info (please complete the following information):**
 - Rom
 - Magisk version
 - Other mods installed

**Additional context**
Every \*shell\* that support *.rc file should read that file if exist. `.bashrc` file in $HOME should overwrite existing `bashrc` in default path usually in `/etc/bash.bashrc`.

**Comment by Zackptg5** [comment]
See here for the paths I have set: https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/blob/master/build_script/patches/bash/config-top.h.patch

The problem is that there is no true $HOME in android. We use to be able to set it to /sdcard but  starting with A11, scoped storage was required which means that /sdcard is no longer accessible by default. Apps require full storage permissions and some terminal apps that are more up to date switched to scoped storage without even having that option making /sdcard inaccessible to those terminal apps.
Long and short, there's no suitable $HOME directory that'd be universal that doesn't require root access in A11+ other than default bash directory I set up.

That being said, I still use /sdcard for now for the apps where it'll work - rather than .bashrc file, modify the /sdcard/.customrc file for your custom bash stuff to get what you want
