### ISSUE TITLE
`ncursesw` is lacking crucial commands.

### ISSUE THREAD

**Issue by SedapnyaTidur** [Zackptg5/Cross-Compiled-Binaries-Android#78]
**Name of binary/ies**
ncursesw
**Description**
Currently the `ncursesw` package only provides `terminfo` stuff and is lacking critical commands like `clear` and `reset`. It is good to have those to clear the scrollback buffer. Sometimes `reset` works as `clear` and vise versa.

**Comment by Zackptg5** [comment]
That's by design, I only use ncurses library as a dependency for some of the binaries. The commands/binaries that it complies conflict with existing android ones which lead to undesired behaviors when I initially tested it long ago. Clear is part of native android toybox and reset is part of busybox (I recommend using osm0sis' by the way - https://github.com/Magisk-Modules-Repo/busybox-ndk)

**Comment by SedapnyaTidur** [comment]
I do have a busybox installed BTW. Unfortunately, there is a good reason why `clear` and `reset` are part of ncurses. Both depends on terminfo and $TERM to do their job correctly. Anyways, it is fine to me. Adding `iconv` and `idn2` in your list would be a good addition too.
